name: CI Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.2

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: List Files
      run: ls -l

    - name: Run Tests
      run: python test.py

    - name: Check Predictions
      run: |
        if ! cmp --silent predict.txt expected_predict.txt; then
          echo "Predictions do not match expected results."
          exit 1
        fi

    - name: Check Synthetic Results
      run: |
        if ! cmp --silent synthetic_results.txt expected_synthetic_results.txt; then
          echo "Synthetic results do not match expected results."
          exit 1
        fi

    - name: Set up CML
      uses: iterative/setup-cml@v1

    - name: Run CML Workflow
      run: cml-runner
