name: CML Tests
on:
  push:
    branches:
      - main
jobs:
  ml-model-training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up CML
        uses: iterative/setup-cml@v2

      - name: Generate Report
        run: |
          python new_model.py --output report.html
          echo '![](./report.html)' >> report.md
          cml comment update --publish report.md --token ${{ secrets.PAT_TOKEN }}
