version: 1
workflows:
  version: 2
  ml-model-training:
    on:
      push:
        branches:
          - main
    jobs:
      - name: Generate Report
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.11.2

          - name: Install dependencies
            run: pip install -r requirements.txt

          - name: Generate Report
            run: |
              python new_model.py --output report.html
              echo '![](./report.html)' >> report.md
              cml comment create --publish report.md
